export const loginPageUrl = 'https://www.saucedemo.com'
export const productPageUrl = 'https://www.saucedemo.com/inventory.html'
export const cartPageUrl = 'https://www.saucedemo.com/cart.html'
export const checkOutInformationPageUrl = 'https://www.saucedemo.com/checkout-step-one.html'
export const checkOutCompletePageUrl = 'https://www.saucedemo.com/checkout-complete.html'
export const checkOutOverViewPageUrl = 'https://www.saucedemo.com/checkout-step-two.html'